// <auto-generated />
using System;
using ControleFinanceiro.Api.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControleFinanceiro.Api.Migrations
{
    [DbContext(typeof(ControleFinanceiroDbContext))]
    [Migration("20240915192840_InitalMigrations")]
    partial class InitalMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ControleFinanceiro.Api.Domain.Entities.ContasAPagar", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<Guid>("PessoasId")
                        .HasColumnType("uuid");

                    b.Property<short>("QuantidadeDeParcelas")
                        .HasColumnType("smallint");

                    b.Property<DateOnly>("UpdateOn")
                        .HasColumnType("date");

                    b.Property<decimal>("ValorAPagar")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PessoasId");

                    b.ToTable("ContasAPagar");
                });

            modelBuilder.Entity("ControleFinanceiro.Api.Domain.Entities.Pessoas", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CadastroDePessoaFisica")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataDeNascimento")
                        .HasColumnType("date");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistroGeral")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorEmConta")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorInvestido")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("ControleFinanceiro.Api.Domain.Entities.ContasAPagar", b =>
                {
                    b.HasOne("ControleFinanceiro.Api.Domain.Entities.Pessoas", "Pessoas")
                        .WithMany()
                        .HasForeignKey("PessoasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoas");
                });
#pragma warning restore 612, 618
        }
    }
}
